export const francLanguage = {
  cmn: 普通话,
  spa: 西班牙语,
  eng: 英语,
  rus: 俄语,
  arb: 标准阿拉伯语,
  ben: 孟加拉,
  hin: 印地语,
  por: 葡萄牙语,
  ind: 印度尼西亚,
  jpn: 日本,
  fra: 法国,
  deu: 德语,
  jav: 爪哇,
  kor: 朝鲜语,
  tel: 泰卢固语,
  vie: 越南,
  mar: 马拉,
  ita: 意大利,
  tam: 泰米尔人,
  tur: 土耳其,
  urd: 乌尔都语,
  guj: 古吉拉特语,
  pol: 抛光,
  ukr: 乌克兰,
  fas: 波斯语,
  kan: 卡纳达语,
  mai: 迈蒂利,
  mal: 马拉雅拉姆语,
  mya: 缅甸语,
  ori: 奥里亚语（宏语言）,
  gax: Borana-Arsi-Guji Oromo,
  swh: Swahili (individual language),
  sun: Sundanese,
  ron: Romanian,
  pan: Panjabi,
  bho: Bhojpuri,
  amh: Amharic,
  hau: Hausa,
  fuv: Nigerian Fulfulde,
  bos: Bosnian (Cyrillic),
  bos: Bosnian (Latin),
  hrv: Croatian,
  nld: Dutch,
  srp: Serbian (Cyrillic),
  srp: Serbian (Latin),
  tha: Thai,
  ckb: Central Kurdish,
  yor: Yoruba,
  uzn: Northern Uzbek (Cyrillic),
  uzn: Northern Uzbek (Latin),
  zlm: Malay (individual language) (Arabic),
  zlm: Malay (individual language) (Latin),
  ibo: Igbo,
  nep: Nepali (macrolanguage),
  ceb: Cebuano,
  skr: Saraiki,
  tgl: Tagalog,
  hun: Hungarian,
  azj: North Azerbaijani (Cyrillic),
  azj: North Azerbaijani (Latin),
  sin: Sinhala,
  koi: Komi-Permyak,
  ell: Modern Greek (1453-),
  ces: Czech,
  run: Rundi,
  bel: Belarusian,
  plt: Plateau Malagasy,
  qug: Chimborazo Highland Quichua,
  mad: Madurese,
  nya: Nyanja,
  zyb: Yongbei Zhuang,
  pbu: Northern Pashto,
  kin: Kinyarwanda,
  zul: Zulu,
  bul: Bulgarian,
  swe: Swedish,
  lin: Lingala,
  som: Somali,
  hms: Southern Qiandong Miao,
  hnj: Hmong Njua,
  ilo: Iloko,
  kaz: Kazakh,
  uig: Uighur (Arabic),
  uig: Uighur (Latin),
  hat: Haitian,
  khm: Khmer,
  aka: Akan,
  hil: Hiligaynon,
  sna: Shona,
  tat: Tatar,
  xho: Xhosa,
  hye: Armenian,
  min: Minangkabau,
  afr: Afrikaans,
  lua: Luba-Lulua,
  sat: Santali,
  bod: Tibetan,
  tir: Tigrinya,
  fin: Finnish,
  slk: Slovak,
  tuk: Turkmen (Cyrillic),
  tuk: Turkmen (Latin),
  dan: Danish,
  nob: Norwegian Bokmål,
  suk: Sukuma,
  als: Tosk Albanian,
  sag: Sango,
  nno: Norwegian Nynorsk,
  heb: Hebrew,
  mos: Mossi,
  tgk: Tajik,
  cat: Catalan,
  sot: Southern Sotho,
  kat: Georgian,
  bcl: Central Bikol,
  glg: Galician,
  lao: Lao,
  lit: Lithuanian,
  umb: Umbundu,
  tsn: Tswana,
  vec: Venetian,
  nso: Pedi,
  ban: Balinese,
  bug: Buginese,
  knc: Central Kanuri,
  kng: Koongo,
  ibb: Ibibio,
  lug: Ganda,
  ace: Achinese,
  bam: Bambara,
  tzm: Central Atlas Tamazight,
  ydd: Eastern Yiddish,
  kmb: Kimbundu,
  lun: Lunda,
  shn: Shan,
  war: Waray (Philippines),
  dyu: Dyula,
  wol: Wolof,
  kir: Kirghiz,
  nds: Low German,
  fuf: Pular,
  mkd: Macedonian,
  vmw: Makhuwa,
  zgh: Standard Moroccan Tamazight,
  ewe: Ewe,
  khk: Halh Mongolian,
  slv: Slovenian,
  ayr: Central Aymara,
  bem: Bemba (Zambia),
  emk: Eastern Maninkakan,
  bci: Baoulé,
  bum: Bulu (Cameroon),
  epo: Esperanto,
  pam: Pampanga,
  tiv: Tiv,
  tpi: Tok Pisin,
  ven: Venda,
  ssw: Swati,
  nyn: Nyankole,
  kbd: Kabardian,
  iii: Sichuan Yi,
  yao: Yao,
  lav: Latvian,
  quz: Cusco Quechua,
  src: Logudorese Sardinian,
  rup: Macedo-Romanian,
  sco: Scots,
  tso: Tsonga,
  rmy: Vlax Romani,
  men: Mende (Sierra Leone),
  fon: Fon,
  nhn: Central Nahuatl,
  dip: Northeastern Dinka,
  kde: Makonde,
  snn: Siona,
  kbp: Kabiyè,
  tem: Timne,
  toi: Tonga (Zambia),
  est: Estonian,
  snk: Soninke,
  cjk: Chokwe,
  ada: Adangme,
  aii: Assyrian Neo-Aramaic,
  quy: Ayacucho Quechua,
  rmn: Balkan Romani,
  bin: Bini,
  gaa: Ga,
  ndo: Ndonga,
};

